serenity.report.encoding = UTF-8
webdriver.driver=chrome
webdriver.base.url=https://www.saucedemo.com/
chrome.switches=--guest;--disable-notifications;--disable-popup-blocking;--disable-save-password-bubble;--disable-features=PasswordManagerOnboarding,PasswordLeakDetection,PasswordManagerAccountStorage,PasswordChangeSubmissionUI
serenity.project.name=SauceDemo E2E Automation
serenity.take.screenshots=FOR_EACH_ACTION
serenity.report.show.step.details=true
headless.mode=false